

package com.woutwerkman.calltreevisualizer.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.woutwerkman.calltreevisualizer.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/src/test/resources/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/src/test/resources/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("deepNesting.kt")
  public void testDeepNesting() {
    runTest("compiler-plugin/src/test/resources/box/deepNesting.kt");
  }

  @Test
  @TestMetadata("nonTrackedFunction.kt")
  public void testNonTrackedFunction() {
    runTest("compiler-plugin/src/test/resources/box/nonTrackedFunction.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/src/test/resources/box/simple.kt");
  }

  @Test
  @TestMetadata("simpleIntrinsics.kt")
  public void testSimpleIntrinsics() {
    runTest("compiler-plugin/src/test/resources/box/simpleIntrinsics.kt");
  }

  @Test
  @TestMetadata("suspendWithReturn.kt")
  public void testSuspendWithReturn() {
    runTest("compiler-plugin/src/test/resources/box/suspendWithReturn.kt");
  }
}
